version: "3.9"

services:
  app:
    build: .
    container_name: crypto-portfolio-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - SERVER_PORT=3000
      - SERVER_HOST=http://db:3000
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=user
      - DB_NAME=crypto-portfolio-db
      - DB_PORT=5432
      - DB_URL=postgresql://user:user@db:5432/crypto-portfolio-db
      - JWT_ACCESS_SECRET=b541f891b929fc9e69bd32638c417a7f766f400c2cb9b3501f464896f1898b9cd8c5c21df0e66c20bf246f4faf74b208dc177819e01bd982ca9f377b01b49d03
      - JWT_REFRESH_SECRET=3e0c8549bd5a4771e257c884b1266c4cbd115578463a269fb578fa58fa3ce8da36b0c1f67f2fb0f52c3c373e0a8724b6d3861201a96d0afea93413afde771487
      - CMC_API_KEY=fa9d544e-2c73-4811-aace-802a1b32ce86
      - CMC_API_URL=https://pro-api.coinmarketcap.com
    depends_on:
      - db
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules
    command: sh -c "pnpm db:generate && pnpm db:migrate && pnpm run dev"

  db:
    image: postgres:latest
    container_name: crypto-portfolio-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=crypto-portfolio-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
